# Part 5:  Algorithmic thinking and primality testing

In this notebook, we go deeper into the nature of *algorithms* -- not only computing things with Python, but reliably computing them efficiently in time and space.  We study two algorithms in detail:  Floyd's cycle-finding algorithm and Pingala's exponentiation algorithm.  We apply the latter to primality-testing, quickly determining whether a very large (hundreds or thousands of digits) number is prime.  

We analyze the **expected performance** of these algorithms using Python's `timeit` function for timing and `randint` function to randomize input parameters.  We also see how the performance depends on the number of **bits** of the input parameters.  In this way, we gently introduce some practical and theoretical issues in computer science.

## Table of Contents

- [Calculations in modular arithmetic](#modcalc)
- [The Miller-Rabin Primality Test](#millerrabin)

<a id='modcalc'></a>

## Calculations in modular arithmetic

### The mod (%) operator

For basic modular arithmetic, one can use Python's "mod operator" `%` to obtain remainders.  There is a conceptual difference between the "mod" of computer programming and the "mod" of number theorists.  In computer programming, "mod" is typically the operator which outputs the remainder after division.  So for a computer scientist, "23 mod 5 = 3", because 3 is the remainder after dividing 23 by 5.

Number theorists (starting with Gauss) take a radical conceptual shift.  A number theorist would write $23 \equiv 3$ mod $5$, to say that 23 is **congruent** to 3 modulo 5.  In this sense "mod 5" (standing for "modulo 5") is a [prepositional phrase](https://www.economist.com/blogs/johnson/2012/08/grammar), describing the "modular world" in which 23 is the same as ("congruent to") 3.

To connect these perspectives, we would say that the computer scientist's statement "23 mod 5 = 3" gives the **natural representative** 3 for the number 23 in the mathematician's "ring of integers mod 5".  (Here "ring" is a term from abstract algebra.)

In [1]:
23 % 5  # What is the remainder after dividing 23 by 5?  What is the natural representative of 23 modulo 5?

3

The miracle that makes modular arithmetic work is that the end-result of a computation "mod m" is not changed if one works "mod m" along the way.  At least this is true if the computation only involves **addition, subtraction, and multiplication**.

In [2]:
((17 + 38) * (105 - 193)) % 13  # Do a bunch of stuff, then take the representative modulo 13.

9

In [3]:
(((17%13) + (38%13)) * ((105%13) - (193%13)) ) % 13 # Working modulo 13 along the way.

9

It might seem tedious to carry out this "reduction mod m" at every step along the way.  But the advantage is that you never have to work with numbers much bigger than the modulus (m) if you can reduce modulo m at each step.

For example, consider the following computation.

In [7]:
3**999 # A very large integer.

440690273160268878963485086584048121988474010917382722554973456075609532448901633180259437950202687321303259232290860785316984860700206303955114241752651224675873408399440267959338258076321613758130133372529539347042982605207698146020522057684695558163502059375160114801849018132346298605821789418305378740276756187926194096742805466102629298972852134694966312536457747390615453312898505588339646862703020142029890479621367604783461882915721944003538122044057700922967618406667

In [5]:
(3**999) % 1000  # What are the last 3 digits of 3 raised to the 999 power?

667

To compute the last three digits of $3^{999}$, Python works with some very large integers along the way.  But what if we could reduce modulo 1000 at every step?  Then, as Python multiplies terms, it will never have to multiply numbers bigger than 1000.  Here is a brute-force implementation.

In [8]:
P = 1  # The "running product" starts at 1.
for i in range(999):  # We repeat the following line 999 times, as i traverses the list [0,1,...,998].
    P = (P * 3)%1000  # We reduce modulo 1000 along the way!
print(P)

667


In this computation, Python never has to work with long integers.  Computations with long integers are time-consuming, and unnecessary if you only care about the result of a computation modulo a small number m.

### Performance analysis

The above loop works quickly, but it is far from optimal.  Let's carry out some **performance analysis** by writing two `powermod` functions.

In [50]:
def powermod_1(base, exponent, modulus):  # The naive approach.
    return (base**exponent) % modulus 

In [51]:
def powermod_2(base, exponent, modulus):
    P = 1 # Start the running product at 1.
    # e = 0
    for i in range(exponent):
        P = (P * base) % modulus
    return P

Now let's compare the performance of these two functions.  It's also good to double check the code in `powermod_2` and run it to check the results.  The reason is that loops like this are classic sources of [Off by One Errors](https://en.wikipedia.org/wiki/Off-by-one_error).  One has to unravel the loop carefully to be completely certain, and testing is a necessity to avoid bugs!

We can compare the performance of the two functions with identical input parameters below.

In [12]:
%timeit powermod_1(3,999,1000)

3.12 µs ± 212 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
%timeit powermod_2(3,999,1000)

111 µs ± 4.84 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


The `powermod_1` function is faster (perhaps by a factor of 8-10) than the `powermod_2` function we designed.  At least, this is the case for inputs in the 2-3 digit range that we sampled.  But why?  We reduced the complexity of the calculation by using the mod operation `%` throughout.  Here are a few issues one might suspect.

1.  The mod operation itself takes a bit of time.  Maybe that time added up in `powermod_2`?
2.  The Python power operation `**` is highly optimized already, and outperforms our while loop.
3.  We used more multiplications than necessary.

It turns out that the mod operation is extremely fast... as in *nanoseconds* (billionths of a second) fast.

In [14]:
%timeit 1238712 % 1237

20.1 ns ± 0.655 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


So the speed difference is probably not due to the number of mod operations.  But the other issues are relevant.  The Python developers have worked hard to make Python run fast -- built-in operations like `**` will almost certainly be faster than any function that you write with a loop in Python.  The developers have written programs in the **C programming language** (typically) to implement operations like `**` (see the [CPython implementation](https://hg.python.org/cpython/file/c7163a7f7cd2/Python/bltinmodule.c#l1505), if you wish); their programs have been **compiled** into **machine code** -- the basic sets of instructions that your computer understands (and that are not meant for people to understand).  When you call a built-in operation like `**`, Python just tells your computer to run the developers' optimized and **precompiled** machine code... this is very fast!  When you run your own loop, there is a lot of Python-related overhead slowing things down.

Still, it is unfortunate to use long integers if you ask Python to compute `(3**999) % 1000`.  The good news is that such modular exponents are so frequently used that the Python developers have a built-in operation:  the `pow` function.

The `pow` function has two versions.  The simplest version `pow(b,e)` raises `b` to the `e` power.  It is the same as computing `b ** e`.  But it also has a modular version!  The command `pow(b,e,m)` raises `b` to the `e` modulo `m`, efficiently reducing modulo `m` along the way.

In [15]:
pow(3,999)  # A long number.

440690273160268878963485086584048121988474010917382722554973456075609532448901633180259437950202687321303259232290860785316984860700206303955114241752651224675873408399440267959338258076321613758130133372529539347042982605207698146020522057684695558163502059375160114801849018132346298605821789418305378740276756187926194096742805466102629298972852134694966312536457747390615453312898505588339646862703020142029890479621367604783461882915721944003538122044057700922967618406667

In [16]:
pow(3,999,1000) # The result, modulo 1000.  

667

In [17]:
pow(3,999) % 1000 # The old way

667

In [18]:
%timeit pow(3,999,1000)

1.41 µs ± 19.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [19]:
%timeit pow(3,999) % 1000

3.01 µs ± 95.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [35]:
t = %timeit -o pow(3,999) % 1000

8.4 µs ± 591 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [24]:
dir(t)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_precision',
 '_repr_pretty_',
 'all_runs',
 'average',
 'best',
 'compile_time',
 'loops',
 'repeat',
 'stdev',
 'timings',
 'worst']

In [32]:
t.all_runs

[0.3101535860914737,
 0.36289896396920085,
 0.31624223990365863,
 0.30396660906262696,
 0.29023010306991637,
 0.2913689570268616,
 0.2967945849522948]

In [26]:
t.compile_time

7.899999999949614e-05

The `pow(b,e,m)` command should give a significant speedup, as compared to the `pow(b,e)` command.  Remember that ns stands for nanoseconds (billionths of a second) and µs stands for microseconds (millionths of a second).

Exponentiation runs so quickly because not only is Python reducing modulo `m` along the way, it is performing a surprisingly small number of multiplications.  In our loop approach, we computed $3^{999}$ by multiplying repeatedly.  There were 999 multiplications!  But consider this carefully -- did we need to perform so many multiplications?  Can you compute $3^{999}$ with far fewer multiplications?  What if you can place results in memory along the way?  

In the next section, we study a very efficient **algorithm** for computing such exponents.  The goal in designing a good algorithm is to create something which runs **quickly**, minimizes the need for **memory**, and runs reliably for all the necessary input values.  Often there are trade-offs between speed and memory usage, but our exponentiation algorithm will be excellent in both respects.  The ideas go back to [Pingala](https://en.wikipedia.org/wiki/Pingala), an Indian mathematician of the 2nd or 3rd century BCE, who developed his ideas to enumerate possible poetic meters (arrangements of long and short syllables into verses of a given length).  

You may wonder why it is necessary to learn the algorithm at all, if Python has an optimized algorithm built into its `pow` command.  First, it is interesting!  But also, we will need to understand the algorithm in finer detail to implement the Miller-Rabin test:  a way of quickly testing whether very large numbers are prime.

### Exercises

1.  Use the `timeit` and `randint` functions to investigate how the speed of the command `pow(a,e,m)` depends on how many digits the numbers `a`, `e`, and `m` have.  Note that `randint(10**(d-1), 10**d - 1)` will produce a random integer with `d` digits.  If you hold two of these variables fixed, consider how the time changes as the third variable is changed.  Which of the three variables has the biggest effect on speed?

### 1.

In [28]:
from numpy.random import randint

In [204]:
# Let's start with these as defaults
a = 3
e = 999
m = 1001

# vary a
print("\nVarying digits of a in command pow(a,{},{}):\n".format(e,m))
for d in range(3, 6):
    a = randint(10**(d-1), 10**d - 1)
    
    t = %timeit -o -q pow(a,e,m)
    avg = t.average
    
    print("{} digits: {}".format(d,avg))
    
    
# vary e
a = 3
e = 999
m = 1001
print("\nVarying digits of e in command pow({},e,{}):\n".format(a,m))
for d in range(3, 6):
    e = randint(10**(d-1), 10**d - 1)
    
    t = %timeit -o -q pow(a,e,m)
    avg = t.average
    
    print("{} digits: {}".format(d,avg))  
    

# vary m
a = 3
e = 999
m = 1001
print("\nVarying digits of n in command pow({},{},m):\n".format(a,e))
for d in range(3, 6):
    m = randint(10**(d-1), 10**d - 1)
    
    t = %timeit -o -q pow(a,e,m)
    avg = t.average
    
    print("{} digits: {}".format(d,avg))


Varying digits of a in command pow(a,999,1001):

3 digits: 1.5319200434272975e-06
4 digits: 1.6050182705699366e-06
5 digits: 1.4341609871439037e-06

Varying digits of e in command pow(3,e,1001):

3 digits: 1.3700062179996166e-06
4 digits: 1.4474605964288847e-06
5 digits: 1.4430504574307374e-06

Varying digits of n in command pow(3,999,m):

3 digits: 1.3423276934273807e-06
4 digits: 1.4956466739968165e-06
5 digits: 1.670693439855573e-06


## Modular dynamics

Now we look at dynamical systems, cycle-finding, and Fermat's Little Theorem.  When we refer to "dynamics" or "dynamical systems," we are talking about something with *initial conditions* and an *evolution process* by which the state changes.  The "state" of the system is typically described by one or more numbers, and the initial conditions describe the starting-state.  The evolution process describes how the state changes at every "tick" of the clock.

For example, the Collatz conjecture is about a dynamical system where...
1.  The state, at any time, is given by a single integer.
2.  We explore various integers as initial conditions.
3.  The state changes according to the following rule:  even numbers are divided by two; odd numbers are tripled, then incremented by one.  

Here is the evolution function for the Collatz conjecture.

In [1]:
def evolve_Collatz(n):
    if n%2 == 0:
        return n//2 # Integer division is a good idea!
    else:
        return 3*n + 1

To study the dynamics of the Collatz process, we could use a simple loop.

In [2]:
state = 7  # The initial condition
time = 0
while time < 20:
    print("At time {}, the state is {}.".format(time, state))
    state = evolve_Collatz(state)
    time += 1

At time 0, the state is 7.
At time 1, the state is 22.
At time 2, the state is 11.
At time 3, the state is 34.
At time 4, the state is 17.
At time 5, the state is 52.
At time 6, the state is 26.
At time 7, the state is 13.
At time 8, the state is 40.
At time 9, the state is 20.
At time 10, the state is 10.
At time 11, the state is 5.
At time 12, the state is 16.
At time 13, the state is 8.
At time 14, the state is 4.
At time 15, the state is 2.
At time 16, the state is 1.
At time 17, the state is 4.
At time 18, the state is 2.
At time 19, the state is 1.


To study dynamical systems more flexibly, we can create a more adaptive function.

In [3]:
def study(init_state, evolve, time_max):
    state = init_state  # The initial condition
    time = 0
    while time < time_max:
        print("At time {}, the state is {}.".format(time, state))
        state = evolve(state)
        time += 1

Before studying this function, we take it for a spin.

In [4]:
study(13,evolve_Collatz, 10)

At time 0, the state is 13.
At time 1, the state is 40.
At time 2, the state is 20.
At time 3, the state is 10.
At time 4, the state is 5.
At time 5, the state is 16.
At time 6, the state is 8.
At time 7, the state is 4.
At time 8, the state is 2.
At time 9, the state is 1.


We have seen just about everything used in the function `study`.  But one parameter might have caught your eye:  `evolve` is a parameter -- an input to the function `study`.  Not only numbers, lists, and arrays can be inputs to functions.  Functions can be inputs to functions!  Here `evolve` is a function, which is studied by the function `study`.  If we want to study a different dynamical system, we can define a new function to study. 

In [5]:
def evolve_seven(n):
    return (14*n) % 100

In [6]:
study(11, evolve_seven, 20) # Start at 11.  Evolve for 20 units of time.

At time 0, the state is 11.
At time 1, the state is 54.
At time 2, the state is 56.
At time 3, the state is 84.
At time 4, the state is 76.
At time 5, the state is 64.
At time 6, the state is 96.
At time 7, the state is 44.
At time 8, the state is 16.
At time 9, the state is 24.
At time 10, the state is 36.
At time 11, the state is 4.
At time 12, the state is 56.
At time 13, the state is 84.
At time 14, the state is 76.
At time 15, the state is 64.
At time 16, the state is 96.
At time 17, the state is 44.
At time 18, the state is 16.
At time 19, the state is 24.


If you know a bit of HTML, you can use it to output your data in a prettier format.  Here is an example, using the HTML and display functions.

In [7]:
from IPython.display import HTML, display # Load the necessary packages.

In [158]:
def study(init_state, evolve, time_max):
    state = init_state  # The initial condition
    time = 0
    state_list = [None] * time_max # Initialize a list of Nones.  Faster than appending!
    while time < time_max:
        state_list[time] = state
        state = evolve(state)
        time += 1
    
    table = [['Time:'] + list(range(time_max)), ['State:'] + state_list] # Put the data in a table with two rows.
    
    display(HTML(
    '<table><tr>{}</tr></table>'.format(
        '</tr><tr>'.join(
            '<td>{}</td>'.format('</td><td>'.join(str(_) for _ in row)) for row in table)
        )
    ))

In [9]:
study(11,evolve_seven, 30) # Now it will look pretty!

You might notice that the dynamical system enters a cycle.  The state at time 2 is 56, and 10 "ticks" later, the state at time 12 is 56.  Since the evolution process does not depend on time, just on state, you'll see another repetition 10 ticks later:  the state at time 22 is 56 also.  In this way, we find that the dynamics *enter a cycle* of length 10, starting at time 2.  (Note that the states at times 0,1 do not repeat!)

It is often useful to find cycles, and this raises interesting problems in computer science.  How might we teach the computer to detect cycles, and how can we do this efficiently in time and space?  The brute-force method is to save the past-states in a list, and then check each state against the previous states for a repetition.  An implementation is below, after we introduce a few more list-tricks.

In [10]:
3 in [1,2,3,4,5] # Python has an "in" operator, to detect membership in a list.

True

In [11]:
6 in [1,2,3,4,5] # 6 is not "in" the list.

False

#### This finds the index of the *first* element n:

In [16]:
[1,2,3,4,5,3].index(3) # Python can also find the *index* of an item in a list.

2

In [13]:
[1,2,3,4,5].index(6) # A ValueError exception is thrown if the item is not found.

ValueError: 6 is not in list

In [175]:
def find_cycle(init_state, evolve, time_max):
    
    state = init_state  # The initial condition
    state_list = [None] * time_max # Initialize a list of Nones.  Faster than appending!
    time = 0
    cycle_found = False # We have not found a cycle yet!
    
    while (time < time_max) and (cycle_found == False):
        
        if state in state_list:
            cycle_found = True
            index_found = state_list.index(state) # Where did we find it?
            time_found = time
        
        state_list[time] = state
        state = evolve(state)
        time += 1
    
#     table = [['Time:'] + list(range(time)), ['State:'] + state_list[:time]] # Put the data in a table with two rows.
#     display(HTML(
#     '<table><tr>{}</tr></table>'.format(
#         '</tr><tr>'.join(
#             '<td>{}</td>'.format('</td><td>'.join(str(_) for _ in row)) for row in table)
#         )
#     ))
    
    if cycle_found:
        # index_found = first occurence
        # time_found = time of first repeat
        return index_found, time_found

In [22]:
find_cycle(11,evolve_seven, 30)

(2, 12)

In [23]:
find_cycle(-1000, evolve_Collatz,50)

(19, 24)

This method of cycle detection is reliable -- it will find the moment when a dynamical system enters a cycle, and the first time the cycle repeats.  But there are two drawbacks to this "brute force" method.  The first drawback is memory -- one must remember all of the previous states in order to search for repetition.  This is not a problem in the examples above, but one can imagine a situation where a cycle is not encountered until after a million repetitions or more.  This could cause memory problems!

The second drawback is speed.  The list method `LIST.index(n)` searches through a list to find the first occurrence of the item `n`.  The amount of time needed is proportional to the length of the list, or rather, the length of the list up to the point where `n` is found (or the end of the list if it's not found).  At time 1, one will need to search through 1 item; at time 2, one will need to search through 2 items; at time 3, one will need to search through 3 items, etc..  So to go through 1000 steps of time, one will end up searching (testing equality) $1 + 2 + 3 + \cdots + 1000$ times.  This can get slow!

So here we introduce a completely different approach to cycle detection, known (perhaps mistakenly) as [Floyd's Algorithm](https://en.wikipedia.org/wiki/Cycle_detection#Floyd's_Tortoise_and_Hare).  The idea is to send two creatures, the tortoise and the hare, through the dynamical system at different speeds, and compare their values to each other at each step of time.  We implement this in a verbose form below.

In [174]:
def Floyd(init_state, evolve, time_max = 1000000):
    
    # The tortoise and hare start in the same state.
    tortoise = init_state
    hare = init_state
    
    # Time and cycle vars
    time = 0
    cycle_found = False
    
    # Stage 1:  The tortoise and hare go through the dynamical system.
    # The tortoise goes one step per unit of time.
    # The hare goes two steps per unit of time.
    # Repeat until they equal each other (or until time hits time_max)
    while (time < time_max) and (cycle_found == False):
        
        time = time + 1
        
        tortoise = evolve(tortoise) # The tortoise goes one step.
        hare = evolve(evolve(hare)) # The hare goes two steps!
        
        if tortoise == hare:
            cycle_found = True
    
    if time == time_max:
#RM         print('Timeout before cycle was found :(')
        return None
    
    # Effectively, the state at "time" equals the state at "2*time" (hare-time)
    # So the cycle length is a divisor of "time", 
    # and the first cycle occurs before "time."
    
    
    # Stage 2:  Find the *beginning* of the cycle. The tortoise starts over.
    time, tortoise = 0, init_state
    
    # The hare is still the previous value... "time" steps ahead of the tortoise. 
    while tortoise != hare:
        time = time + 1
        tortoise = evolve(tortoise)
        hare = evolve(hare)
    
    # The tortoise is at the beginning of the first cycle.
    # Move the hare back to the location of the tortoise.
    # Set the hare moving forward until it finds the end of the first cycle.
    hare = evolve(tortoise) # One step ahead of the tortoise
    cycle_length = 1
    while tortoise != hare:
        cycle_length = cycle_length + 1
        hare = evolve(hare)
    # Now the tortoise is at the beginning of the first cycle, 
    # and the hare is at the end of the first cycle.
    
    return time, cycle_length, tortoise # Functions can return multiple outputs, as a tuple.

Now let's try out Floyd's algorithm.  To understand the result, compare it to the study below.

In [25]:
Floyd(-1000, evolve_Collatz)

(19, 5, -14)

In [26]:
study(-1000, evolve_Collatz, 50)

In [27]:
find_cycle(-1000, evolve_Collatz,50)

(19, 24)

## Exercises

1.  Use %timeit to compare the speed of Floyd and find_cycle.  But be *very* careful!  Before you use %timeit, remove all print commands, so that your computer doesn't try to print a million things to your browser tab!  Back up your work first.  For your experiments, it's good to have a dynamical system with long cycle-lengths.  Try variations of the following:

`def evolve_fun(n):
    return (n*n*n + 17)%1000000`

2.  Suppose that each time you call the `evolve` function, you have to pay a dollar.  How much will Floyd's algorithm cost, if the first cycle begins at time $t$ and has length $\ell$? 

3.  Consider the following dynamical system:  Let $p$ be a prime number, and let $a$ be an integer between $1$ and $p-1$.  Begin at an integer $k$.  Evolve by sending an integer $z$ to $(a \cdot z) \% p$.  How are the cycle lengths related to $p-1$?  Try a few different primes $p$ and integers $a$ to look for patterns. 

### 1.

In [183]:
def evolve_fun(n):
    return (n*n*n + 17)%1000000

In [182]:
def evolve_other_fun(n):
    return (n*n + 3*n - 1) % 10007777

In [181]:
def evolve_super_fun(n):
    return (n**(n+1) + 8) % 101

In [198]:
%timeit find_cycle(17, evolve_fun, 1000000)

117 ms ± 7.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [199]:
%timeit Floyd(17, evolve_fun)

9.26 µs ± 413 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [202]:
%timeit find_cycle(17, evolve_super_fun, 1000000)

109 ms ± 1.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [187]:
%timeit Floyd(17, evolve_super_fun)

20.1 µs ± 584 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Floyd is 10,000 times faster in these two!

In [200]:
%timeit find_cycle(17, evolve_other_fun, 1000000)

4.5 s ± 35.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [201]:
%timeit Floyd(17, evolve_other_fun)

433 µs ± 26 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### 3. It looks like the cycle lengths divide the number $p-1$!!

In [191]:
p = 7
a = 4
k = 1

def evolve_prime(n):
    return (n*a)%p

Floyd(k, evolve_prime)[1]

3

In [194]:
p = 11
a = 3
k = 1

def evolve_prime(n):
    return (n*a)%p

Floyd(k, evolve_prime)[1]

5

In [196]:
p = 13
a = 44
k = 5

def evolve_prime(n):
    return (n*a)%p

Floyd(k, evolve_prime)[1]

4

<a id='millerrabin'></a>

## The Miller-Rabin primality test

### Fermat's Little Theorem and the ROO property of primes

Fermat's Little Theorem states that if $p$ is a prime number, and $GCD(a,p) = 1$, then 
$$a^{p-1} \equiv 1 \text{ mod } p.$$

It can be proven by showing that the cycle-lengths for the "multiplication-by-$a$-mod-$p$" dynamical system are all divisors of $p-1$.  

Under the assumptions above, if we ask Python to compute `(a**(p-1))%p`, or even better, `pow(a,p-1,p)`, the result should be 1.  We use and refine this idea to develop a powerful and practical primality test.  Let's begin with a few checks of Fermat's Little Theorem.

In [28]:
pow(3,36,37)  # a = 3, p = 37, p-1 = 36

1

In [29]:
pow(17,100,101) # 101 is prime.

1

In [30]:
pow(303, 100, 101)  # Why won't we get 1?

0

In [32]:
# 91 = 7*13
pow(5,90,91) # What's the answer?

64

In [33]:
pow(7,12318, 12319) # What's the answer?

1331

We can learn something from the previous two examples.  Namely, 91 and 12319 are **not** prime numbers.  We say that 7 **witnesses** the non-primality of 12319.  Moreover, we learned this fact without actually finding a factor of 12319!  Indeed, the factors of 12319 are 97 and 127, which have no relationship to the "witness" 7.

In this way, Fermat's Little Theorem -- a statement about prime numbers -- can be turned into a way of discovering that numbers are not prime.  After all, if $p$ is not prime, then what are the chances that $a^{p-1} \equiv 1$ mod $p$ by coincidence?  

In [34]:
pow(3,90,91)

1

Well, ok.  Sometimes coincidences happen.  We say that 3 is a **bad witness** for 91, since 91 is not prime, but $3^{90} \equiv 1$ mod $91$.  But we could try multiple bases (witnesses).  We can expect that someone (some base) will witness the nonprimality.  Indeed, for the non-prime 91 there are many good witnesses (ones that detect the nonprimality).

In [35]:
for witness in range(1,20):
    flt = pow(witness, 90, 91)
    if flt == 1:
        print("{} is a bad witness.".format(witness))
    else:
        print("{} raised to the 90th power equals {}, mod 91".format(witness, flt))

1 is a bad witness.
2 raised to the 90th power equals 64, mod 91
3 is a bad witness.
4 is a bad witness.
5 raised to the 90th power equals 64, mod 91
6 raised to the 90th power equals 64, mod 91
7 raised to the 90th power equals 77, mod 91
8 raised to the 90th power equals 64, mod 91
9 is a bad witness.
10 is a bad witness.
11 raised to the 90th power equals 64, mod 91
12 is a bad witness.
13 raised to the 90th power equals 78, mod 91
14 raised to the 90th power equals 14, mod 91
15 raised to the 90th power equals 64, mod 91
16 is a bad witness.
17 is a bad witness.
18 raised to the 90th power equals 64, mod 91
19 raised to the 90th power equals 64, mod 91


For some numbers -- the [Carmichael numbers](https://en.wikipedia.org/wiki/Carmichael_number) -- there are more bad witnesses than good witnesses.  For example, take the Carmichael number 41041, which is not prime ($41041 = 7 \cdot 11 \cdot 13 \cdot 41$).  

In [36]:
for witness in range(1,20):
    flt = pow(witness, 41040, 41041)
    if flt == 1:
        print("{} is a bad witness.".format(witness))
    else:
        print("{} raised to the 41040th power equals {}, mod 41041".format(witness, flt))

1 is a bad witness.
2 is a bad witness.
3 is a bad witness.
4 is a bad witness.
5 is a bad witness.
6 is a bad witness.
7 raised to the 41040th power equals 29316, mod 41041
8 is a bad witness.
9 is a bad witness.
10 is a bad witness.
11 raised to the 41040th power equals 18656, mod 41041
12 is a bad witness.
13 raised to the 41040th power equals 22100, mod 41041
14 raised to the 41040th power equals 29316, mod 41041
15 is a bad witness.
16 is a bad witness.
17 is a bad witness.
18 is a bad witness.
19 is a bad witness.


For Carmichael numbers, it turns out that finding a good witness is just as difficult as finding a factor.  Although Carmichael numbers are rare, they demonstrate that Fermat's Little Theorem by itself is not a great way to be certain of primality.  Effectively, Fermat's Little Theorem can often be used to quickly prove that a number **is not prime**... but it is not so good if we want to be sure that a number **is prime**.

The Miller-Rabin primality test will refine the Fermat's Little Theorem test, by cleverly taking advantage of another property of prime numbers.  We call this the ROO (Roots Of One) property:  if $p$ is a prime number, and $x^2 \equiv 1$ mod $p$, then $x \equiv 1$ or $x \equiv -1$ mod $p$.

In [37]:
for x in range(41):  
    if x*x % 41 == 1:
        print("{} squared is congruent to 1, mod 41.".format(x))  # What numbers do you think will be printed?

1 squared is congruent to 1, mod 41.
40 squared is congruent to 1, mod 41.


Note that we use "natural representatives" when doing modular arithmetic in Python.  So the only numbers whose square is 1 mod 41 are 1 and 40.  (Note that 40 is the natural representative of -1, mod 41).  If we consider the "square roots of 1" with a composite modulus, we find more (as long as the modulus has at least two odd prime factors).

In [38]:
for x in range(91):
    if x*x % 91 == 1:
        print("{} squared is congruent to 1, mod 91.".format(x))  # What numbers do you think will be printed?

1 squared is congruent to 1, mod 91.
27 squared is congruent to 1, mod 91.
64 squared is congruent to 1, mod 91.
90 squared is congruent to 1, mod 91.


We have described two properties of prime numbers, and therefore two possible indicators that a number is not prime.

1.  If $p$ is a number which violates Fermat's Little Theorem, then $p$ is not prime.

2.  If $p$ is a number which violates the ROO property, then $p$ is not prime.

The Miller Rabin test will combine these indicators.  But first we have to introduce an ancient algorithm for exponentiation.

### Pingala's exponentiation algorithm

If we wish to compute $5^{90}$ mod $91$, without the `pow` command, we don't have to carry out 90 multiplications.  Instead, we carry out **Pingala's algorithm**.  To understand this algorithm, we begin with the desired exponent (e.g. $e=90$), and carry out a series of steps:  replace $e$ by $e/2$ if $e$ is even, and replace $e$ by $(e-1) / 2$ if $e$ is odd.  Repeat this until the exponent is decreased to zero.  It's a process like the Collatz $3n+1$ process... but it continually makes positive integers smaller.

The following function carries out this process on any input $e$.

In [39]:
def Pingala(e):
    current_number = e
    while current_number > 0:
        if current_number%2 == 0:
            current_number = current_number // 2
            print("Exponent {} BIT 0".format(current_number))
        if current_number%2 == 1:
            current_number = (current_number - 1) // 2
            print("Exponent {} BIT 1".format(current_number))

In [40]:
Pingala(90)

Exponent 45 BIT 0
Exponent 22 BIT 1
Exponent 11 BIT 0
Exponent 5 BIT 1
Exponent 2 BIT 1
Exponent 1 BIT 0
Exponent 0 BIT 1


The codes "BIT 1" and "BIT 0" tell us what happened at each step, and allow the process to be reversed.  In a line with BIT 0, the exponent gets **doubled** as one goes **up** one line (e.g., from 11 to 22).  In a line with BIT 1, the exponent gets **doubled then increased by 1** as one goes **up** one line (e.g., from 2 to 5).

We can use these BIT codes in order to compute an exponent.  Below, we follow the BIT codes to compute $5^{90}$.

In [41]:
n = 1  # This is where we start.
n = n*n * 5 # BIT 1 is interpreted as square-then-multiply-by-5, since the exponent is doubled then increased by 1.
n = n*n  # BIT 0 is interpreted as squaring, since the exponent is doubled.
n = n*n * 5 # BIT 1
n = n*n * 5 # BIT 1 again.
n = n*n # BIT 0
n = n*n * 5 # BIT 1
n = n*n # BIT 0

In [42]:
print(n)  # What we just computed.
print(5**90) # I hope these match!!

807793566946316088741610050849573099185363389551639556884765625
807793566946316088741610050849573099185363389551639556884765625


Note that along the way, we carried out 11 multiplications (count the `*` symbols), and didn't have to remember too many numbers along the way.  So this process was efficient in both time and memory.  We just followed the BIT code.  The number of multiplications is bounded by twice the number of BITs, since each BIT requires at most two multiplications (squaring then multiplication by 5) to execute.

Why did we call the code a BIT code?  It's because the code consists precisely of the bits (binary digits) of the exponent 90!  Since computers store numbers in binary, the computer "knows" the BIT code as soon as it knows the exponent.  In Python, the `bin` command recovers the binary expansion of a number.

In [43]:
bin(90)  # Compare this to the sequence of bits, from bottom up.

'0b1011010'

Python outputs binary expansions as strings, beginning with `'0b'`.  To summarize, we can compute an exponent like $b^e$ by the following process:

**Pingala's Exponentiation Algorithm**

1.  Set the number to 1.

2.  Read the bits of $e$, from left to right.  
    a. When the bit is zero, square the number.   
    b. When the bit is one, square the number, then multiply by $b$.
    
3.  Output the resulting number.

In [44]:
def pow_Pingala(base,exponent):
    result = 1
    bitstring = bin(exponent)[2:] # Chop off the '0b' part of the binary expansion of exponent
    for bit in bitstring: # Iterates through the "letters" of the string.  Here the letters are '0' or '1'.
        if bit == '0':
            result = result*result
        if bit == '1':
            result = result*result * base
    return result

In [45]:
pow_Pingala(5,90)

807793566946316088741610050849573099185363389551639556884765625

It is straightforward to modify Pingala's algorithm to compute exponents in modular arithmetic.  Just reduce along the way.

In [46]:
def powmod_Pingala(base,exponent,modulus):
    result = 1
    bitstring = bin(exponent)[2:] # Chop off the '0b' part of the binary expansion of exponent
    for bit in bitstring: # Iterates through the "letters" of the string.  Here the letters are '0' or '1'.
        if bit == '0':
            result = (result*result) % modulus 
        if bit == '1':
            result = (result*result * base) % modulus
    return result

In [47]:
powmod_Pingala(5,90,91)

64

Let's compare the performance of our new modular exponentiation algorithm.

In [48]:
%timeit powmod_Pingala(3,999,1000)  # Pingala's algorithm, modding along the way.

2.68 µs ± 43.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [52]:
%timeit powermod_1(3,999,1000)  # Raise to the power, then mod, using Python built-in exponents.

3.07 µs ± 39.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [53]:
%timeit powermod_2(3,999,1000)  #  Multiply 999 times, modding along the way.

117 µs ± 1.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [54]:
%timeit pow(3,999,1000)  #  Use the Python built-in modular exponent.

1.41 µs ± 38.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


The fully built-in modular exponentiation `pow(b,e,m)` command is probably the fastest.  But our implementation of Pingala's algorithm isn't bad -- it probably beats the simple `(b**e) % m` command (in the `powermod_1` function), and it's certainly faster than our naive loop in `powermod_2`.  

One can quantify the efficiency of these algorithms by analyzing how the **time** depends on the **size** of the input parameters.  For the sake of exposition, let us keep the base and modulus constant, and consider how the time varies with the size of the exponent.

As a function of the exponent $e$, our `powmod_Pingala` algorithm required some number of multiplications, bounded by twice the number of bits of $e$.  The number of bits of $e$ is approximately $\log_2(e)$.  The size of the numbers multiplied is bounded by the size of the (constant) modulus.  In this way, the time taken by the `powmod_Pingala` algorithm should be $O(\log(e))$, meaning bounded by a constant times the logarithm of the exponent.

Contrast this with the slow `powermod_2` algorithm, which performs $e$ multiplications, and has thus has runtime $O(e)$.

### The Miller-Rabin test

Pingala's algorithm is effective for computing exponents, in ordinary arithmetic or in modular arithmetic.  In this way, we can look for violations of Fermat's Little Theorem as before, to find witnesses to non-primality.  But if we look more closely at the algorithm... we can sometimes find violations of the ROO property of primes.  This strengthens the primality test.

To see this, we create out a "verbose" version of Pingala's algorithm for modular exponentiation.

In [55]:
def powmod_verbose(base, exponent, modulus):
    result = 1
    print("Computing {} raised to {}, modulo {}.".format(base, exponent, modulus))
    print("The current number is {}".format(result))
    bitstring = bin(exponent)[2:] # Chop off the '0b' part of the binary expansion of exponent
    for bit in bitstring: # Iterates through the "letters" of the string.  Here the letters are '0' or '1'.
        sq_result = result*result % modulus  # We need to compute this in any case.
        if bit == '0':
            print("BIT 0:  {} squared is congruent to {}, mod {}".format(result, sq_result, modulus))
            result = sq_result 
        if bit == '1':
            newresult = (sq_result * base) % modulus
            print("BIT 1:  {} squared times {} is congruent to {}, mod {}".format(result, base, newresult, modulus))
            result = newresult
    return result

In [56]:
powmod_verbose(2,560,561)  # 561 is a Carmichael number.

Computing 2 raised to 560, modulo 561.
The current number is 1
BIT 1:  1 squared times 2 is congruent to 2, mod 561
BIT 0:  2 squared is congruent to 4, mod 561
BIT 0:  4 squared is congruent to 16, mod 561
BIT 0:  16 squared is congruent to 256, mod 561
BIT 1:  256 squared times 2 is congruent to 359, mod 561
BIT 1:  359 squared times 2 is congruent to 263, mod 561
BIT 0:  263 squared is congruent to 166, mod 561
BIT 0:  166 squared is congruent to 67, mod 561
BIT 0:  67 squared is congruent to 1, mod 561
BIT 0:  1 squared is congruent to 1, mod 561


1

The function has displayed every step in Pingala's algorithm.  The final result is that $2^{560} \equiv 1$ mod $561$.  So in this sense, $2$ is a bad witness.  For $561$ is not prime (3 is a factor), but it does not violate Fermat's Little Theorem when $2$ is the base.

But within the verbose output above, there is a violation of the ROO property.  The penultimate line states that "67 squared is congruent to 1, mod 561".  But if 561 were prime, only 1 and 560 are square roots of 1.  Hence this penultimate line implies that 561 is not prime (again, without finding a factor!).  

This underlies the Miller-Rabin test.  We carry out Pingala's exponentiation algorithm to compute $b^{p-1}$ modulo $p$.  If we find a violation of ROO along the way, then the test number $p$ is not prime.  And if, at the end, the computation does not yield $1$, we have found a Fermat's Little Theorem (FLT) violation, and the test number $p$ is not prime.

The function below implements the Miller-Rabin test on a number $p$, using a given base.

In [57]:
def Miller_Rabin(p, base):
    '''
    Tests whether p is prime, using the given base.
    The result False implies that p is definitely not prime.
    The result True implies that p **might** be prime.
    It is not a perfect test!
    '''
    
    result = 1
    exponent = p-1
    modulus = p
    bitstring = bin(exponent)[2:] # Chop off the '0b' part of the binary expansion of exponent
    
    for bit in bitstring: # Iterates through the "letters" of the string.  Here the letters are '0' or '1'.
        
        # We need to compute this in any case because we either double
        # the exponent, or double then increase by one
        sq_result = result*result % modulus
       
        # ROO violation is that x^2 = 1 for x NOT equal +-1
        if sq_result == 1:
            if (result != 1) and (result != exponent):  # Note that exponent is congruent to -1, mod p.
                return False  # a ROO violation occurred, so p is not prime
        
        # Play the game
        if bit == '0':
            result = sq_result 
        elif bit == '1':
            result = (sq_result * base) % modulus
    
    # FLT violation is that b^(p-1) not equal 1 mod p
    if result != 1:
        return False  # a FLT violation occurred, so p is not prime.
    
    return True  # If we made it this far, no violation occurred and p might be prime.

In [58]:
 Miller_Rabin(101,6)

True

How good is the Miller-Rabin test?  Will this modest improvement (looking for ROO violations) improve the reliability of witnesses?  Let's see how many witnesses observe the nonprimality of 41041.

In [59]:
for witness in range(2,20):
    MR = Miller_Rabin(41041, witness) 
    
    if MR: 
        print("{} is a bad witness.".format(witness))
    else:
        print("{} detects that 41041 is not prime.".format(witness))

2 detects that 41041 is not prime.
3 detects that 41041 is not prime.
4 detects that 41041 is not prime.
5 detects that 41041 is not prime.
6 detects that 41041 is not prime.
7 detects that 41041 is not prime.
8 detects that 41041 is not prime.
9 detects that 41041 is not prime.
10 detects that 41041 is not prime.
11 detects that 41041 is not prime.
12 detects that 41041 is not prime.
13 detects that 41041 is not prime.
14 detects that 41041 is not prime.
15 detects that 41041 is not prime.
16 is a bad witness.
17 detects that 41041 is not prime.
18 detects that 41041 is not prime.
19 detects that 41041 is not prime.


In fact, one can prove that at least 3/4 of the witnesses will detect the non-primality of any non-prime.  Thus, if you keep on asking witnesses at random, your chances of detecting non-primality increase exponentially!  In fact, the witness 2 suffices to check whether any number is prime or not up to 2047.  In other words, if $p < 2047$, then $p$ is prime if and only if `Miller_Rabin(p,2)` is `True`.  Just using the witnesses 2 and 3 suffice to check primality for numbers up to a million (1373653, to be precise, according to [Wikipedia](https://en.wikipedia.org/wiki/Miller%E2%80%93Rabin_primality_test).)

The general strategy behind the Miller-Rabin test then is to use just a few witnesses for smallish potential primes (say, up to $2^{64}$).  For larger numbers, try some number $x$ (like 20 or 50) random bases.  If the tested number **is** composite, then the probability of all witnesses reporting `True` is is less than $1 / 4^x$.  With 50 random witnesses, the chance that a composite number tests as prime is less than $10^{-30}$.  

Note that these are statements about **conditional probability**.  In more formal language,
$$\text{Prob} \left( \text{tests prime} \ \vert \ \text{ is composite} \right) < \frac{1}{4^{\# \text{witnesses} } }.$$
As those who study medical testing know, this probability differs from the probability that most people care about:  the probability that a number is prime, given that it tests prime.  The relationship between the two probabilities is given by Bayes Theorem, and depends on the **prevalence** of primes among the sample.  If our sample consists of numbers of absolute value about $N$, then the prevalence of primes will be about $1 / \log(N)$, and the probability of primality given a positive test result can be approximated. 
$$\text{Prob} \left( \text{ is prime } \ \vert \ \text{ tests prime } \right) > 1 - \frac{\log(N) - 1}{4^{\# \text{witnesses}}}.$$
As one chooses more witnesses, this probability becomes extremely close to $1$.

In [80]:
from mpmath import *
# The mpmath package allows us to compute with arbitrary precision!
# It has specialized functions for log, sin, exp, etc.., with arbitrary precision.
# It is probably installed with your version of Python.

In [81]:
def prob_prime(N, witnesses):
    '''
    Conservatively estimates the probability of primality, given a positive test result.
    N is an approximation of the size of the tested number.
    witnesses is the number of witnesses.
    '''
    mp.dps = witnesses # mp.dps is the number of digits of precision.  We adapt this as needed for input.
    prob_prime = 1 - (log(N) - 1) / (4**witnesses)
    print(str(100*prob_prime)+"% chance of primality") # Use str to convert mpmath float to string for printing.

In [82]:
prob_prime(10**100, 50) # Chance of primality with 50 witnesses, if a 100-digit number is tested.

99.999999999999999999999999981914692482445195916316% chance of primality


We implement the Miller-Rabin test for primality in the `is_prime` function below.

In [83]:
from random import randint

In [85]:
# 2**64 isn't huge at all
2**64

18446744073709551616

In [86]:
def is_prime(p, witnesses=50):  # witnesses is a parameter with a default value.
    '''
    Tests whether a positive integer p is prime.
    For p < 2^64, the test is deterministic, using known good witnesses.
    Good witnesses come from a table at Wikipedia's article on the Miller-Rabin test,
    based on research by Pomerance, Selfridge and Wagstaff, Jaeschke, Jiang and Deng.
    For larger p, a number (by default, 50) of witnesses are chosen at random.
    '''
    if (p%2 == 0): # Might as well take care of even numbers at the outset!
        if p == 2:
            return True
        else:
            return False 
    
    if p > 2**64:  # We use the probabilistic test for large p.
        trial = 0
        while trial < witnesses:
            trial = trial + 1
            witness = randint(2,p-2) # A good range for possible witnesses
            
            # False definitely means not prime. Because contrapositive off FLT or ROO
            if Miller_Rabin(p,witness) == False:
                return False
        # probably prime
        return True
    
    else:  # We use a determinisic test for p <= 2**64.
        
        verdict = Miller_Rabin(p,2)
        if p < 2047:
            return verdict # The witness 2 suffices.
        
        verdict = verdict and Miller_Rabin(p,3)
        if p < 1373653:
            return verdict # The witnesses 2 and 3 suffice.
        
        verdict = verdict and Miller_Rabin(p,5)
        if p < 25326001:
            return verdict # The witnesses 2,3,5 suffice.
        
        verdict = verdict and Miller_Rabin(p,7)
        if p < 3215031751:
            return verdict # The witnesses 2,3,5,7 suffice.
        
        verdict = verdict and Miller_Rabin(p,11)
        if p < 2152302898747:
            return verdict # The witnesses 2,3,5,7,11 suffice.
        
        verdict = verdict and Miller_Rabin(p,13)
        if p < 3474749660383:
            return verdict # The witnesses 2,3,5,7,11,13 suffice.
        
        verdict = verdict and Miller_Rabin(p,17)
        if p < 341550071728321:
            return verdict # The witnesses 2,3,5,7,11,17 suffice.
        
        verdict = verdict and Miller_Rabin(p,19) and Miller_Rabin(p,23)
        if p < 3825123056546413051:
            return verdict # The witnesses 2,3,5,7,11,17,19,23 suffice.
        
        verdict = verdict and Miller_Rabin(p,29) and Miller_Rabin(p,31) and Miller_Rabin(p,37)
        return verdict # The witnesses 2,3,5,7,11,17,19,23,29,31,37 suffice for testing up to 2^64. 

In [87]:
is_prime(1000000000000066600000000000001)  # This is Belphegor's prime.

True

How fast is our new `is_prime` function?  Let's give it a try.

In [88]:
%timeit is_prime(234987928347928347928347928734987398792837491)

117 µs ± 3.43 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [89]:
%timeit is_prime(1000000000000066600000000000001)

3.1 ms ± 62.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


The results will probably on the order of a millisecond, perhaps even a tenth of a millisecond ($10^{-4}$ seconds) for non-primes!  That's much faster than looking for factors, for numbers of this size.  In this way, we can test primality of numbers of hundreds of digits!

For an application, let's find some Mersenne primes.  Recall that a Mersenne prime is a prime of the form $2^p - 1$.  Note that when $2^p - 1$ is prime, it must be the case that $p$ is a prime too.  We will quickly find the Mersenne primes with $p$ up to 1000 below!

In [92]:
for p in range(1,1000):
    if is_prime(p):  # We only need to check these p.
        M = 2**p - 1 # A candidate for a Mersenne prime.
        if is_prime(M):
            if M <= 2**64:
                print("2^{} - 1 = {} is a Mersenne prime.".format(p,M))
            else:
                print("2^{} - 1 = {} is probably a Mersenne prime.".format(p,M))

2^2 - 1 = 3 is a Mersenne prime.
2^3 - 1 = 7 is a Mersenne prime.
2^5 - 1 = 31 is a Mersenne prime.
2^7 - 1 = 127 is a Mersenne prime.
2^13 - 1 = 8191 is a Mersenne prime.
2^17 - 1 = 131071 is a Mersenne prime.
2^19 - 1 = 524287 is a Mersenne prime.
2^31 - 1 = 2147483647 is a Mersenne prime.
2^61 - 1 = 2305843009213693951 is a Mersenne prime.
2^89 - 1 = 618970019642690137449562111 is probably a Mersenne prime.
2^107 - 1 = 162259276829213363391578010288127 is probably a Mersenne prime.
2^127 - 1 = 170141183460469231731687303715884105727 is probably a Mersenne prime.
2^521 - 1 = 6864797660130609714981900799081393217269435300143305409394463459185543183397656052122559640661454554977296311391480858037121987999716643812574028291115057151 is probably a Mersenne prime.
2^607 - 1 = 531137992816767098689588206552468627329593117727031923199444138200403559860852242739162502265229285668889329486246501015346579337652707239409519978766587351943831270835393219031728127 is probably a Mersenne prime.


### Exercises

1.  If $2^p - 1$ is a Mersenne prime, then Euclid proved that $(2^p - 1) \cdot 2^{p-1}$ is a perfect number.  Find all the (even) perfect numbers up to $2^{1000}$.  (Note:  nobody has ever found an odd perfect number.  Euler proved that all even perfect numbers arise from Mersenne primes by Euclid's recipe.)

2.  The Fermat sequence is the sequence of numbers 3, 5, 257, 65537, etc., of the form $2^{2^n} + 1$ for $n \geq 0$.  Test the primality of these numbers for $n$ up to 10.

3.  Why does the is_prime function (using Miller-Rabin) run more quickly on non-primes than it does on primes?

4.  Compare the performance of the new `is_prime` function to "trial division" (looking for factors up to the square root of the test number).  Which is faster for small numbers (1-digit, 2-digits, 3-digits, etc.)?  Adapt the `is_prime` function to perform trial division for small numbers in order to optimize performance.  

5.  Estimate the probability that a randomly chosen 10-digit number is prime, by running is_prime on a large number of samples.  How does this probability vary as the number of digits increases (e.g., from 10 digits to 11 digits to 12 digits, etc., onto 20 digits)?

### 1.

In [102]:
perfect = 0
p = 2

while perfect <= 2**1000:
    if is_prime(p):  # We only need to check these p.
        M = 2**p - 1 # A candidate for a Mersenne prime.
        if is_prime(M):
            perfect = M*(2**(p-1))
            
            if M <= 2**64:
                print("{} is a perfect number.\n".format(perfect))
            else:
                print("{} is *probably* a perfect number.\n".format(perfect))
    
    # Increment the prime to test
    p += 1

6 is a perfect number.

28 is a perfect number.

496 is a perfect number.

8128 is a perfect number.

33550336 is a perfect number.

8589869056 is a perfect number.

137438691328 is a perfect number.

2305843008139952128 is a perfect number.

2658455991569831744654692615953842176 is a perfect number.

191561942608236107294793378084303638130997321548169216 is *probably* a perfect number.

13164036458569648337239753460458722910223472318386943117783728128 is *probably* a perfect number.

14474011154664524427946373126085988481573677491474835889066354349131199152128 is *probably* a perfect number.

23562723457267347065789548996709904988477547858392600710143027597506337283178622239730365539602600561360255566462503270175052892578043215543382498428777152427010394496918664028644534128033831439790236838624033171435922356643219703101720713163527487298747400647801939587165936401087419375649057918549492160555646976 is *probably* a perfect number.



### 2.

In [106]:
for n in range(0,11):
    F = 2**(2**n) +1
    if is_prime(F):
        print("F_{} = {} is prime".format(n,F))
    else:
        print("F_{} = {} is not prime".format(n,F))

F_0 = 3 is prime
F_1 = 5 is prime
F_2 = 17 is prime
F_3 = 257 is prime
F_4 = 65537 is prime
F_5 = 4294967297 is not prime
F_6 = 18446744073709551617 is not prime
F_7 = 340282366920938463463374607431768211457 is not prime
F_8 = 115792089237316195423570985008687907853269984665640564039457584007913129639937 is not prime
F_9 = 13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084097 is not prime
F_10 = 179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424865485276302219601246094119453082952085005768838150682342462881473913110540827237163350510684586298239947245938479716304835356329624224137217 is not prime


### 3.
The Miller-Rabin based prime test terminates faster for nonprimes because it only takes a single violation of FLT or ROO to definitely not be prime. On the other hand, it takes several trials, across several witnesses, to confirm a potential prime.

### 4.

In [114]:
def slow_is_prime(n):
    sq = int(sqrt(n))
    d = 2
    while d <= sq:
        if n%d == 0:
            return False
        d += 1
    return True

In [141]:
trials = 3

for number_digits in range(1,7):
    print("\n{} trials for {} digits:\n".format(trials, number_digits))
    for i in range(trials):
        n = randint(10**(number_digits-1), 10**(number_digits)-1)
        print("\nTest on n = {}:".format(n))
        %timeit slow_is_prime(n)


3 trials for 1 digits:


Test on n = 7:
9.06 µs ± 248 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

Test on n = 9:
8.4 µs ± 202 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

Test on n = 2:
9.02 µs ± 188 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

3 trials for 2 digits:


Test on n = 63:
9.05 µs ± 146 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

Test on n = 89:
10.1 µs ± 630 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

Test on n = 70:
9.49 µs ± 463 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

3 trials for 3 digits:


Test on n = 138:
9.72 µs ± 364 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

Test on n = 434:
10.1 µs ± 143 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

Test on n = 285:
9.34 µs ± 320 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

3 trials for 4 digits:


Test on n = 8083:
16 µs ± 583 ns per loop (mean ± std. dev. of 7 runs, 100000 loo

In [146]:
trials = 3

for number_digits in range(1,7):
    print("\n{} trials for {} digits:\n".format(trials, number_digits))
    for i in range(trials):
        n = randint(10**(number_digits-1), 10**(number_digits)-1)
        print("Test on n = {}:".format(n))
        %timeit is_prime(n)


3 trials for 1 digits:

Test on n = 5:
1.68 µs ± 68.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
Test on n = 2:
268 ns ± 6.36 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
Test on n = 3:
1.63 µs ± 121 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

3 trials for 2 digits:

Test on n = 98:
244 ns ± 9.39 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
Test on n = 13:
2.04 µs ± 87.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
Test on n = 22:
253 ns ± 15.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

3 trials for 3 digits:

Test on n = 839:
3.61 µs ± 109 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
Test on n = 625:
3.46 µs ± 121 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
Test on n = 939:
3.61 µs ± 400 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

3 trials for 4 digits:

Test on n = 9216:
245 ns ± 7.88 ns per loop (mean ± std. dev. of 7 runs, 1000000 lo

### 5.

In [148]:
# Test 5000 random n digit numbers for primality, then prints distribution
for number_digits in range(10,21):
    S = 0
    for i in range(5000):
        n = randint(10**(number_digits-1), 10**number_digits)
        S += is_prime(n)
    print("Percent primes among {} digit numbers: {}%".format(number_digits, (S/5000)*100))

Percent primes among 10 digit numbers: 4.34%
Percent primes among 11 digit numbers: 4.04%
Percent primes among 12 digit numbers: 3.7800000000000002%
Percent primes among 13 digit numbers: 3.26%
Percent primes among 14 digit numbers: 3.1199999999999997%
Percent primes among 15 digit numbers: 3.18%
Percent primes among 16 digit numbers: 2.48%
Percent primes among 17 digit numbers: 2.82%
Percent primes among 18 digit numbers: 2.5%
Percent primes among 19 digit numbers: 2.04%
Percent primes among 20 digit numbers: 2.54%
